graph TD
  N1["app.ts"]
  N2["features/add-recipe/add-recipe.ts"]
  N3["features/admin-panel/activity-log/activity-log.ts"]
  N4["features/admin-panel/admin-panel.ts"]
  N5["features/admin-panel/user-management/edit-user-dialog/edit-user-dialog.ts"]
  N6["features/admin-panel/user-management/user-management.ts"]
  N7["features/auth/auth.ts"]
  N8["features/body/body.ts"]
  N9["features/footer/footer.ts"]
  N10["features/header/header.ts"]
  N11["features/meal-details/meal-details.ts"]
  N12["features/settings/admin-settings/admin-settings.ts"]
  N13["features/settings/settings.ts"]
  N14["features/settings/user-settings/user-settings.ts"]
  N15["shared/confirm-dialog/confirm-dialog.ts"]
  N1 --> N9
  N1 --> N10
  N3 --> N15
  N4 --> N3
  N4 --> N6
  N6 --> N5
  N6 --> N15
  N8 --> N15
  N11 --> N15
  N12 --> N15
  N13 --> N12
  N13 --> N14
  N14 --> N15
